# Variables
[env]
FUZZER_NAME = 'fuzzer_binutils'
CARGO_TARGET_DIR = { value = "${PROJECT_DIR}/target", condition = { env_not_set = [
	"CARGO_TARGET_DIR"
] } }

PROFILE = { value = "release", condition = { env_not_set = ["PROFILE"] } }
PROFILE_DIR = { source = "${PROFILE}", default_value = "release", mapping = { "release" = "release", "dev" = "debug" }, condition = { env_not_set = [
  "PROFILE_DIR",
] } }

LIBAFL_CC = '${CARGO_TARGET_DIR}/${PROFILE_DIR}/libafl_cc'
LIBAFL_CXX = '${CARGO_TARGET_DIR}/${PROFILE}/libafl_cxx'
LIBAFL_LIBTOOL = '${CARGO_TARGET_DIR}/${PROFILE}/libafl_libtool'
FUZZER = '${CARGO_TARGET_DIR}/${PROFILE_DIR}/${FUZZER_NAME}'
PROJECT_DIR = { script = ["pwd"] }

[tasks.unsupported]
script_runner = "@shell"
script = '''
echo "Cargo-make not integrated yet on this platform"
'''

# binutils
[tasks.binutils]
linux_alias = "binutils_unix"
mac_alias = "binutils_mac"
windows_alias = "binutils_windows"

[tasks.binutils_archive]
condition = { files_not_exist = ["./binutils-2.34.tar.gz"] }
script_runner = "@shell"
script = '''
wget https://ftp.gnu.org/gnu/binutils/binutils-2.34.tar.gz
'''

[tasks.binutils_unix]
condition = { files_not_exist = ["./binutils-2.34"] }
script_runner = "@shell"
script = '''
tar -xvf binutils-2.34.tar.gz > /dev/null
'''
dependencies = ["binutils_archive"]

# Compilers
[tasks.cxx]
linux_alias = "cxx_unix"
mac_alias = "cxx_unix"
windows_alias = "unsupported"

[tasks.cxx_unix]
command = "cargo"
args = ["build", "--profile", "${PROFILE}"]

[tasks.cc]
linux_alias = "cc_unix"
mac_alias = "cc_unix"
windows_alias = "unsupported"

[tasks.cc_unix]
command = "cargo"
args = ["build", "--profile", "${PROFILE}"]

# Library
[tasks.lib]
linux_alias = "lib_unix"
mac_alias = "lib_unix"
windows_alias = "unsupported"

[tasks.lib_unix]
script_runner = "@shell"
script = '''
cd binutils-2.34 && CC="${CARGO_TARGET_DIR}/${PROFILE_DIR}/libafl_cc" CXX="${CARGO_TARGET_DIR}/${PROFILE_DIR}/libafl_cxx" ./configure --enable-shared=no --with-pic=yes --enable-gold=no --enable-ld=no --disable-lto --enable-stage1-languages=all
cd "${PROJECT_DIR}"
make -C binutils-2.34 CC="${CARGO_TARGET_DIR}/${PROFILE_DIR}/libafl_cc" CXX="${CARGO_TARGET_DIR}/${PROFILE_DIR}/libafl_cxx" LIBTOOL=${CARGO_TARGET_DIR}/${PROFILE_DIR}/libafl_libtool
'''
dependencies = ["binutils", "cxx", "cc"]

# Harness
[tasks.fuzzer]
linux_alias = "fuzzer_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.fuzzer_unix]
command = "${CARGO_TARGET_DIR}/${PROFILE_DIR}/libafl_cxx"
args = [
	"FIXME",
	"-o",
	"${FUZZER_NAME}",
]
dependencies = ["lib", "cxx", "cc"]

# Run the fuzzer
[tasks.run]
linux_alias = "run_unix"
mac_alias = "unsupported"
windows_alias = "unsupported"

[tasks.run_unix]
script_runner = "@shell"
script = '''
./${FUZZER_NAME}.coverage_asan --broker-port 21337 --cores 0 --input ./corpus
'''
dependencies = ["fuzzer"]

# Clean up
[tasks.clean]
linux_alias = "clean_unix"
mac_alias = "clean_unix"
windows_alias = "unsupported"

[tasks.clean_unix]
# Disable default `clean` definition
clear = true
script_runner = "@shell"
script = '''
rm -f ./${FUZZER_NAME}
make -C binutils-2.34 clean
cargo clean
'''
